"""init

Revision ID: 0941d4cd0361
Revises: 7d7e4e138623
Create Date: 2025-04-11 01:37:27.623928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0941d4cd0361'
down_revision: Union[str, None] = '7d7e4e138623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPERATIONAL', 'DEGRADED', 'FULL_OUTAGE', 'PARTIAL_OUTAGE', 'MAINTENANCE', name='servicestatus'), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    # ### end Alembic commands ###
