"""Add all new

Revision ID: 222cd938951e
Revises: 4b272ea447d0
Create Date: 2025-04-13 14:03:11.450360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222cd938951e'
down_revision: Union[str, None] = '4b272ea447d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affected_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('org_id', sa.String(), nullable=False))
    op.drop_constraint('events_service_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('events_service_id_fkey', 'events', 'services', ['service_id'], ['id'])
    op.drop_column('events', 'org_id')
    op.drop_table('affected_services')
    # ### end Alembic commands ###
